language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-feed haova/udagram-api-feed:v1
  - docker tag udagram-api-user haova/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push haova/udagram-api-feed:v1
  - docker push haova/udagram-api-user:v1
